--- 
backend: 
  branch: main
  name: git-gateway
  repo: arturataide/test-deti
collections: 
  - 
    create: true
    fields: 
      - 
        label: Title
        name: title
        widget: string
      - 
        label: "Publish Date"
        name: date
        widget: datetime
      - 
        label: "Intro Blurb"
        name: description
        widget: text
      - 
        label: Image
        name: image
        required: false
        widget: image
      - 
        label: Body
        name: body
        widget: markdown
    folder: site/content/post
    label: Post
    name: post
  - 
    files: 
      - 
        fields: 
          - 
            label: Title
            name: title
            widget: string
          - 
            fields: 
              - 
                label: Amount
                name: amount
                widget: string
              - 
                label: Date
                name: date
                widget: string
            label: Money
            name: money
            widget: object
          - 
            label: Subtitle
            name: subtitle
            widget: string
          - 
            label: Image
            name: image
            widget: image
          - 
            fields: 
              - 
                label: Heading
                name: heading
                widget: string
              - 
                label: Text
                name: text
                widget: text
            label: Blurb
            name: blurb
            widget: object
          - 
            fields: 
              - 
                label: Heading
                name: heading
                widget: string
              - 
                label: Text
                name: text
                widget: text
            label: Intro
            name: intro
            widget: object
          - 
            fields: 
              - 
                label: Image
                name: image
                widget: image
              - 
                label: Text
                name: text
                widget: text
            label: Products
            name: products
            widget: list
          - 
            fields: 
              - 
                label: Heading
                name: heading
                widget: string
              - 
                label: Text
                name: text
                widget: text
            label: Values
            name: values
            widget: object
          - 
            field: 
              label: Partner
              name: partner
              widget: image
            label: "Partners"
            name: partners
            widget: list
        file: site/content/_index.md
        label: "Home Page"
        name: home
      - 
        fields: 
          - 
            fields: 
              - 
                label: IBAN
                name: iban
                widget: string
              - 
                label: BIC
                name: bic
                widget: string
              - 
                label: Address
                name: address
                widget: string
              - 
                label: Bank
                name: bank
                widget: string
            label: "Bank Details"
            name: bank_details
            widget: object
          - 
            field: 
              label: Item
              name: item
              widget: string
            label: "Help Items"
            name: help_items
            widget: list
          - 
            field: 
              label: Item
              name: item
              widget: string
            label: "Points Depot"
            name: points_depot
            widget: list
          - 
            field: 
              label: Item
              name: item
              widget: string
            label: "Collection Points"
            name: collection_points
            widget: list
        file: site/content/Soutenir-lUkraine/_index.md
        label: "Soutenir l'Ukraine"
        name: Soutenir-lUkraine
      - 
        fields: 
          - 
            label: Title
            name: title
            widget: string
          - 
            label: Logo
            name: logo
            widget: image
          - 
            label: Body
            name: body
            widget: markdown
          - 
            fields: 
              - 
                label: Heading
                name: heading
                widget: string
              - 
                label: Email
                name: email
                widget: text
              - 
                label: Address
                name: address
                widget: text
              - 
                label: "Postal Code"
                name: postcode
                widget: text
            label: "Contact Entries"
            name: contact_entries
            widget: list
        file: site/content/contacts/_index.md
        label: "Contact Page"
        name: contacts
      - 
        fields: 
          - 
            label: Title
            name: title
            widget: string
          - 
            label: Image
            name: image
            widget: image
          - 
            label: Heading
            name: heading
            widget: string
          - 
            label: Description
            name: description
            widget: string
          - 
            fields: 
              - 
                label: Heading
                name: heading
                widget: string
              - 
                label: Description
                name: description
                widget: text
              - 
                fields: 
                  - 
                    label: Image
                    name: image
                    widget: image
                  - 
                    label: Text
                    name: text
                    widget: text
                label: Blurbs
                name: blurbs
                widget: list
            label: Intro
            name: intro
            widget: object
          - 
            fields: 
              - 
                label: Heading
                name: heading
                widget: string
              - 
                label: Description
                name: description
                widget: text
              - 
                fields: 
                  - 
                    label: Image
                    name: image
                    widget: image
                  - 
                    label: Alt
                    name: alt
                    widget: string
                label: Image1
                name: image1
                widget: object
              - 
                fields: 
                  - 
                    label: Image
                    name: image
                    widget: image
                  - 
                    label: Alt
                    name: alt
                    widget: string
                label: Image2
                name: image2
                widget: object
              - 
                fields: 
                  - 
                    label: Image
                    name: image
                    widget: image
                  - 
                    label: Alt
                    name: alt
                    widget: string
                label: Image3
                name: image3
                widget: object
            label: Main
            name: main
            widget: object
          - 
            fields: 
              - 
                label: Quote
                name: quote
                widget: string
              - 
                label: Author
                name: author
                widget: string
            label: Testimonials
            name: testimonials
            widget: list
          - 
            label: Full_image
            name: full_image
            widget: image
          - 
            fields: 
              - 
                label: Heading
                name: heading
                widget: string
              - 
                label: Description
                name: description
                widget: string
              - 
                fields: 
                  - 
                    label: Plan
                    name: plan
                    widget: string
                  - 
                    label: Price
                    name: price
                    widget: string
                  - 
                    label: Description
                    name: description
                    widget: string
                  - 
                    label: Items
                    name: items
                    widget: list
                label: Plans
                name: plans
                widget: list
            label: Pricing
            name: pricing
            widget: object
        file: site/content/products/_index.md
        label: "Products Page"
        name: products
      - 
        fields: 
          - 
            label: Title
            name: title
            widget: string
          - 
            label: Image
            name: image
            widget: image
          - 
            fields: 
              - 
                label: Heading
                name: heading
                widget: string
              - 
                label: Text
                name: text
                widget: text
              - 
                label: Image
                name: imageUrl
                widget: image
            label: Values
            name: values
            widget: list
        file: site/content/values/_index.md
        label: "Values Page"
        name: values
    label: Pages
    name: pages
media_folder: site/static/img
public_folder: img
