backend:
  branch: main
  name: git-gateway
  repo: arturataide/test-deti
collections:
  - create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Intro Blurb
        name: description
        widget: text
      - label: Image
        name: image
        required: false
        widget: image
      - label: Body
        name: body
        widget: markdown
    folder: site/content/post
    label: Post
    name: post
  - files:
      - file: site/content/_index.md
        label: Home Page
        name: home
        fields:
          - label: Title
            name: title
            widget: string
          - label: Presentation
            name: presentation
            widget: text
          - fields:
              - label: Spent
                name: spent
                widget: string
              - label: Collected
                name: collected
                widget: string
              - label: Date
                name: date
                widget: string
            label: Money
            name: money
            widget: object
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Image
            name: image
            widget: image
          - fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
            label: Intro
            name: intro
            widget: object
          - field:
              label: Partner
              name: partner
              widget: image
            label: Partners
            name: partners
            widget: list        
      - file: site/content/Soutenir-lUkraine/_index.md
        label: Soutenir l'Ukraine
        name: Soutenir-lUkraine
        fields:
          - fields:
              - label: IBAN
                name: iban
                widget: string
              - label: BIC
                name: bic
                widget: string
              - label: Address
                name: address
                widget: string
              - label: Bank
                name: bank
                widget: string
            label: Bank Details
            name: bank_details
            widget: object
          - field:
              label: Item
              name: item
              widget: string
            label: Help Items
            name: help_items
            widget: list
          - field:
              label: Item
              name: item
              widget: string
            label: Points Depot
            name: points_depot
            widget: list
          - field:
              label: Item
              name: item
              widget: string
            label: Collection Points
            name: collection_points
            widget: list
      - file: site/content/contacts/_index.md
        label: Contact Page
        name: contacts   
        fields:
          - label: Title
            name: title
            widget: string
          - label: Logo
            name: logo
            widget: image
          - label: Body
            name: body
            widget: markdown
          - fields:
              - label: Heading
                name: heading
                widget: string
              - label: Email
                name: email
                widget: text
              - label: Address
                name: address
                widget: text
              - label: Postal Code
                name: postcode
                widget: text
            label: Contact Entries
            name: contact_entries
            widget: list   
      - file: site/content/about-us/_index.md
        label: About Us
        name: about-us
        fields:
          - label: Description
            name: description
            type: text
          - label: Uploaded Files
            name: uploaded_files
            widget: list
            - label: File Name
              name: filename
              widget: string
            - label: PDF File
              name: pdf_file
              widget: file
          - label: Team
            name: team
            widget: list
            - label: Name
              name: name
              widget: string
            - label: Title
              name: title
              widget: string
            - label: Photo
              name: photo
              widget: image
    label: Pages
    name: pages
media_folder: site/static/img
public_folder: img
